server:
  port: 8760

eureka:
  instance:
    leaseExpirationDurationInSeconds: 11 # EUREKA_SERVER 服务端间隔多久没收到心跳信息，移除instance
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
  server:
    peer-node-connect-timeout-ms: 1000