server:
  port: 8088
#
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: 10.0.75.1:9092,10.0.75.1:9093,10.0.75.1:9094
#      enable-auto-commit: true
#      group-id: next
#      auto-offset-reset: latest

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver