server:
  port: 8764

spring:
  application:
    name: eureka-consume

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

eureka-consume:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

## Important, this default is close
feign:
  hystrix:
    enabled: true

ribbon:
  eager-load:
    enabled: true
    clients: eureka-provider
logging:
  config: classpath:log4j2.yml

## none-effective
hystrix:
  threadpool:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000